"""Generate BACKLOG.md: the measurement queues for outstanding corpus work.

Runs every named measurement tool and writes what it measured into
BACKLOG.md as a work queue. The file is a candidate list for someone to
read -- never a gate, and never an instruction to act. Authored
dispositions live in TODO.md.

    just backlog
    uv run python tools/backlog.py
"""

from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

from qualc import audit, provenance_hrefs
from qualc.card_completeness import check_card
from qualc.cli import load
from qualc.pandoc_batch import PandocServer

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "BACKLOG.md"


def head_rev() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def corpus_sections() -> list[tuple[str, list[str]]]:
    """Audit-family checks over parsed cards, with full orphan id lists."""
    with PandocServer() as pandoc:
        parsed, wiki_pages, errors = load(REPO, pandoc)
    if errors:
        return [
            (
                "corpus-validation",
                [f"corpus does not validate: {len(errors)} error(s); first: {errors[0]}"],
            )
        ]
    sections: list[tuple[str, list[str]]] = []
    for name, fn in audit.CHECKS.items():
        sections.append((name, fn(parsed).violations))
    sections.append(("orphans", sorted(audit.orphan_ids(parsed, wiki_pages))))
    return sections


def provenance_sections() -> list[tuple[str, list[str]]]:
    return [(check.name, check.findings) for check in provenance_hrefs.run(provenance_hrefs.ALL)]


def completeness_sections() -> list[tuple[str, list[str]]]:
    findings: list[str] = []
    for path in sorted((REPO / "corpus").rglob("*.md")):
        issues = check_card(path)
        if issues:
            findings.append(f"{path.stem}: {', '.join(issues)}")
    return [("incomplete-metadata", findings)]


def render(sections: list[tuple[str, list[str]]], rev: str) -> str:
    lines = [
        "# Work queues (generated)",
        "",
        "Regenerated by `just backlog`. Measurements only — candidates to read,",
        "never a gate, never an instruction to act.",
        "Authored dispositions live in `TODO.md`.",
        "",
        f"Rev: `{rev}` · Generated: {date.today().isoformat()}",
        "",
    ]
    for name, findings in sections:
        lines.append(f"## {name} ({len(findings)})")
        lines.append("")
        if findings:
            lines.extend(f"- {finding}" for finding in findings)
        else:
            lines.append("ok")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    rev = head_rev()
    if OUT.exists() and f"Rev: `{rev}`" in OUT.read_text()[:200]:
        print(f"{OUT.relative_to(REPO)}: up to date at {rev}")
        return
    sections = corpus_sections() + provenance_sections() + completeness_sections()
    OUT.write_text(render(sections, rev))
    total = sum(len(findings) for _name, findings in sections)
    print(f"{OUT.relative_to(REPO)}: {len(sections)} queues, {total} finding(s)")


if __name__ == "__main__":
    main()
