"""Regenerate `queues/C-unsolved-cards.md`: every problem with no solution.

A card leaves the queue by gaining a solution section, so the file is a
measurement rather than a ledger: it is rewritten from the corpus and never
hand-edited. Issue #2 is what empties it.

    just unsolved
    uv run python tools/unsolved_queue.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

from qualc import index
from qualc.model import ParsedCard, discover, parse_cards_with
from qualc.pandoc_batch import PandocServer

REPO = Path(__file__).resolve().parent.parent


def unsolved(parsed: list[ParsedCard]) -> list[ParsedCard]:
    """The same rule `just sample-unsolved` draws from, over the parsed corpus.

    Solved means the card carries its own solution section. Solutions are not
    standalone cards, so there is no second relation-based solved state.
    """
    return [item for item in parsed if item.card.kind == "problem" and not any(kind == "solution" for kind, _text in item.sections)]


def render(cards: list[ParsedCard]) -> str:
    ordered = sorted((c.card.id, c.card.title) for c in cards)
    lines = [
        "# Document queue C: Unsolved problem cards",
        "",
        f"{len(cards)} problem cards have no solution section. These are",
        "the cards issue #2 targets: write a Lamport-style structured proof for each.",
        "",
        "Regenerated by `just unsolved`, and by the commit gate whenever a commit touches",
        "the corpus. A card leaves this list by gaining a solution, so the boxes are a",
        "measurement and not a ledger -- ticking one by hand does not survive the next",
        "commit, and writing the solution removes the line.",
        "",
        "## Count",
        "",
    ]
    lines += [f"- Problems: {len(cards)}", "", f"## Problems ({len(cards)})", ""]
    lines += [f'- [ ] {card_id} — "{title}"' for card_id, title in ordered]
    lines.append("")
    return "\n".join(lines)


def load_cards(root: Path) -> list[ParsedCard]:
    """Parse and validate exactly the inputs that determine Queue C.

    Wiki prose, assets, publications, and rendered-site links do not affect whether a
    problem card has a solution section.  Keeping them out of this measurement also
    lets the commit hook evaluate a temporary-index snapshot without materializing the
    full repository.
    """
    with PandocServer() as pandoc:
        parsed, errors = parse_cards_with(pandoc, discover(root / "corpus"))
    if not errors:
        errors = index.validate(parsed, index.load_vocabularies(root / "vocabularies", root / "wiki"))
    if errors:
        raise SystemExit(f"corpus does not validate: {len(errors)} error(s); first: {errors[0]}")
    return parsed


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=REPO)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    out = root / "queues" / "C-unsolved-cards.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    rendered = render(unsolved(load_cards(root)))
    if out.exists() and out.read_text() == rendered:
        print(f"{out.relative_to(root)}: up to date")
        return
    out.write_text(rendered)
    print(f"{out.relative_to(root)}: rewritten")


if __name__ == "__main__":
    main()
