"""Regenerate `queues/C-unsolved-cards.md`: every problem with no solution.

A card leaves the queue by gaining a solution section, so the file is a
measurement rather than a ledger: it is rewritten from the corpus and never
hand-edited. Issue #2 is what empties it.

    just unsolved
    uv run python tools/unsolved_queue.py
"""

from __future__ import annotations

import argparse
import re
import subprocess
from collections.abc import ItemsView
from pathlib import Path

from pydantic import TypeAdapter
from qualc import index
from qualc.model import Card, ParsedCard, discover, parse_cards_with, split_front_matter
from qualc.pandoc_batch import PandocServer

REPO = Path(__file__).resolve().parent.parent

QUEUE_LINE = re.compile(r'^- \[ \] (?P<id>\S+) — "(?P<title>.*)"$')
SOLUTION_OPEN = re.compile(r"^:::\s*(?:solution|\{[^}\n]*\.solution(?:\s+[^}]*)?\})\s*$", re.M)
CARD_ADAPTER: TypeAdapter[Card] = TypeAdapter(Card)


def queue_entries(text: str) -> dict[str, str]:
    """Parse the generated queue into ``{card id: title}``."""
    out: dict[str, str] = {}
    for line in text.splitlines():
        match = QUEUE_LINE.match(line)
        if match:
            out[match.group("id")] = match.group("title")
    return out


def queue_entry_from_text(text: str, path: Path) -> tuple[str, str] | None:
    """Return one unsolved queue entry from a staged card, without starting Pandoc."""
    meta, body = split_front_matter(text, path)
    card = CARD_ADAPTER.validate_python(meta)
    if card.kind != "problem" or SOLUTION_OPEN.search(body):
        return None
    return card.id, card.title


def _git(root: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=root, text=True, capture_output=True, check=check)


def _git_text(root: Path, spec: str) -> str | None:
    result = _git(root, "show", spec, check=False)
    return result.stdout if result.returncode == 0 else None


def staged_card_changes(root: Path) -> list[tuple[Path | None, Path | None]]:
    """Return ``(old_path, new_path)`` pairs for staged card changes."""
    result = _git(root, "diff", "--cached", "--name-status", "--find-renames", "--", "corpus/collections")
    changes: list[tuple[Path | None, Path | None]] = []
    for line in result.stdout.splitlines():
        parts = line.split("\t")
        status = parts[0][0]
        old_path: Path | None
        new_path: Path | None
        if status == "R":
            old_path, new_path = Path(parts[1]), Path(parts[2])
        elif status == "D":
            old_path, new_path = Path(parts[1]), None
        else:
            old_path, new_path = (Path(parts[1]) if status != "A" else None), Path(parts[1])
        if (old_path and old_path.suffix == ".md") or (new_path and new_path.suffix == ".md"):
            changes.append((old_path, new_path))
    return changes


def incremental_from_staged(root: Path) -> str:
    """Update Queue C from the staged card diff, using HEAD's generated queue as base."""
    baseline = _git_text(root, "HEAD:queues/C-unsolved-cards.md")
    if baseline is None:
        raise SystemExit("HEAD has no queues/C-unsolved-cards.md; run a full rebuild")
    entries = queue_entries(baseline)
    for old_path, new_path in staged_card_changes(root):
        if old_path is not None:
            old_text = _git_text(root, f"HEAD:{old_path.as_posix()}")
            if old_text is not None:
                old_entry = queue_entry_from_text(old_text, old_path)
                if old_entry is not None:
                    entries.pop(old_entry[0], None)
        if new_path is not None:
            new_text = _git_text(root, f":{new_path.as_posix()}")
            if new_text is None:
                raise SystemExit(f"cannot read staged card: {new_path}")
            new_entry = queue_entry_from_text(new_text, new_path)
            if new_entry is not None:
                entries[new_entry[0]] = new_entry[1]
    return render_entries(entries.items())


def unsolved(parsed: list[ParsedCard]) -> list[ParsedCard]:
    """The same rule `just sample-unsolved` draws from, over the parsed corpus.

    Solved means the card carries its own solution section. Solutions are not
    standalone cards, so there is no second relation-based solved state.
    """
    return [item for item in parsed if item.card.kind == "problem" and not any(kind == "solution" for kind, _text in item.sections)]


def render_entries(entries: list[tuple[str, str]] | ItemsView[str, str]) -> str:
    ordered = sorted(entries)
    lines = [
        "# Document queue C: Unsolved problem cards",
        "",
        f"{len(ordered)} problem cards have no solution section. These are",
        "the cards issue #2 targets: write a Lamport-style structured proof for each.",
        "",
        "Regenerated by `just unsolved`, and by the commit gate whenever a commit touches",
        "the corpus. A card leaves this list by gaining a solution, so the boxes are a",
        "measurement and not a ledger -- ticking one by hand does not survive the next",
        "commit, and writing the solution removes the line.",
        "",
        "## Count",
        "",
    ]
    lines += [f"- Problems: {len(ordered)}", "", f"## Problems ({len(ordered)})", ""]
    lines += [f'- [ ] {card_id} — "{title}"' for card_id, title in ordered]
    lines.append("")
    return "\n".join(lines)


def render(cards: list[ParsedCard]) -> str:
    return render_entries([(c.card.id, c.card.title) for c in cards])


def load_cards(root: Path) -> list[ParsedCard]:
    """Parse and validate exactly the inputs that determine Queue C.

    Wiki prose, assets, publications, and rendered-site links do not affect whether a
    problem card has a solution section.  Keeping them out of this measurement also
    lets the commit hook evaluate a temporary-index snapshot without materializing the
    full repository.
    """
    with PandocServer() as pandoc:
        parsed, errors = parse_cards_with(pandoc, discover(root / "corpus"))
    if not errors:
        errors = index.validate(parsed, index.load_vocabularies(root / "vocabularies", root / "wiki"))
    if errors:
        raise SystemExit(f"corpus does not validate: {len(errors)} error(s); first: {errors[0]}")
    return parsed


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=REPO)
    parser.add_argument("--incremental-staged", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    out = root / "queues" / "C-unsolved-cards.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    rendered = incremental_from_staged(root) if args.incremental_staged else render(unsolved(load_cards(root)))
    if out.exists() and out.read_text() == rendered:
        print(f"{out.relative_to(root)}: up to date")
        return
    out.write_text(rendered)
    print(f"{out.relative_to(root)}: rewritten")


if __name__ == "__main__":
    main()
