"""Regenerate `queues/C-unsolved-cards.md`: every problem with no solution.

A card leaves the queue by gaining a solution section, so the file is a
measurement rather than a ledger: it is rewritten from the corpus and never
hand-edited. Issue #2 is what empties it.

    just unsolved
    uv run python tools/unsolved_queue.py
"""

from __future__ import annotations

from pathlib import Path

from qualc.cli import load
from qualc.model import ParsedCard
from qualc.pandoc_batch import PandocServer

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "queues" / "C-unsolved-cards.md"


def unsolved(parsed: list[ParsedCard]) -> list[ParsedCard]:
    """The same rule `just sample-unsolved` draws from, over the parsed corpus.

    Solved means the card carries its own solution section. Solutions are not
    standalone cards, so there is no second relation-based solved state.
    """
    return [item for item in parsed if item.card.kind == "problem" and not any(kind == "solution" for kind, _text in item.sections)]


def render(cards: list[ParsedCard]) -> str:
    ordered = sorted((c.card.id, c.card.title) for c in cards)
    lines = [
        "# Document queue C: Unsolved problem cards",
        "",
        f"{len(cards)} problem cards have no solution section. These are",
        "the cards issue #2 targets: write a Lamport-style structured proof for each.",
        "",
        "Regenerated by `just unsolved`, and by the commit gate whenever a commit touches",
        "the corpus. A card leaves this list by gaining a solution, so the boxes are a",
        "measurement and not a ledger -- ticking one by hand does not survive the next",
        "commit, and writing the solution removes the line.",
        "",
        "## Count",
        "",
    ]
    lines += [f"- Problems: {len(cards)}", "", f"## Problems ({len(cards)})", ""]
    lines += [f'- [ ] {card_id} — "{title}"' for card_id, title in ordered]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    with PandocServer() as pandoc:
        parsed, _wiki_pages, errors = load(REPO, pandoc)
    if errors:
        raise SystemExit(f"corpus does not validate: {len(errors)} error(s); first: {errors[0]}")
    rendered = render(unsolved(parsed))
    if OUT.exists() and OUT.read_text() == rendered:
        print(f"{OUT.relative_to(REPO)}: up to date")
        return
    OUT.write_text(rendered)
    print(f"{OUT.relative_to(REPO)}: rewritten")


if __name__ == "__main__":
    main()
